### ISSUE TITLE
Difference between upper case and lower case causes UPM error

### ISSUE THREAD

**Issue by laicasaane** [CareBoo/Serially#56]
I suspect that for Unity `GUIEvent`  and `GuiEvent` are different so it doesn't recognize `GUIEvent.cs.meta` as the meta file of `GuiEvent.cs`

![image](https://user-images.githubusercontent.com/1594982/90330462-0c90cb80-dfd7-11ea-8032-0520a25f523a.png)

**Comment by jasonboukheir** [comment]
Hey, thanks for letting me know, should be an easy fix!
