### ISSUE TITLE
Build don't work on unity 2021.1

### ISSUE THREAD

**Issue by sttrox** [CareBoo/Serially#69]
https://github.com/CareBoo/Serially/blob/c26b833f5327794955d619cd60dce39b9234e14c/Editor/TypePickerWindow.cs#L134-L138

In unity 2021.1 it's don't working because List have Refresh
https://docs.unity3d.com/2021.1/Documentation/ScriptReference/UIElements.ListView.Refresh.html

**Comment by jasonboukheir** [comment]
Thanks! I'm adding a fix and a test case
